### ISSUE TITLE
no matches for kind "HelmChart" in version "k3s.cattle.io/v1"

### ISSUE THREAD

**Issue by outbackdingo** [apk8s/k3s-gitlab#1]
kubectl create -f ./k8s/0000-global/001-cert-manager-helm.yml 
error: unable to recognize "./k8s/0000-global/001-cert-manager-helm.yml": no matches for kind "HelmChart" in version "k3s.cattle.io/v1"

**Comment by cjimti** [comment]
it's now **helm.cattle.io/v1** I'll get it fixed in the tutorial
