### ISSUE TITLE
restore from previous server

### ISSUE THREAD

**Issue by outbackdingo** [apk8s/k3s-gitlab#2]
yes i noticed it had changed, im good now its deployed, however ......
ok, so not a bug, more a simple question, we backed up our previous dockerized gitlab, and moved it to the k3s gitlab server, though i cant seem to find anything on how to restore this data to the new server, gunna be hard to manually configure 900+ repos... any help / insight?

**Comment by cjimti** [comment]
I have no clue what the best practices for Gitlab migrations are. I would check Gitlab docs and community forums.
